// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/PostUserAuth/PostUserAuth.proto

package go_micro_srv_PostUserAuth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1876a5556762d136, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IDCard               string   `protobuf:"bytes,3,opt,name=IDCard,proto3" json:"IDCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_1876a5556762d136, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Request) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Request) GetIDCard() string {
	if m != nil {
		return m.IDCard
	}
	return ""
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1876a5556762d136, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.PostUserAuth.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostUserAuth.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostUserAuth.Response")
}

func init() {
	proto.RegisterFile("proto/PostUserAuth/PostUserAuth.proto", fileDescriptor_1876a5556762d136)
}

var fileDescriptor_1876a5556762d136 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x0f, 0xc8, 0x2f, 0x2e, 0x09, 0x2d, 0x4e, 0x2d, 0x72, 0x2c, 0x2d, 0xc9, 0x40, 0xe1,
	0xe8, 0x81, 0xe5, 0x85, 0x24, 0xd3, 0xf3, 0xf5, 0x72, 0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x8a, 0x8b,
	0xca, 0xf4, 0x90, 0x15, 0x28, 0x49, 0x73, 0xb1, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a,
	0x09, 0x70, 0x31, 0x17, 0x27, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a,
	0xd1, 0x5c, 0xec, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0xc1, 0xa9,
	0xc5, 0xc5, 0x99, 0xf9, 0x79, 0x9e, 0x2e, 0x50, 0x25, 0x08, 0x01, 0x21, 0x29, 0x2e, 0x8e, 0xa0,
	0xd4, 0xc4, 0x1c, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x24, 0x9c, 0x2f, 0x24, 0xc6, 0xc5,
	0xe6, 0xe9, 0xe2, 0x9c, 0x58, 0x94, 0x22, 0xc1, 0x0c, 0x96, 0x81, 0xf2, 0x94, 0x2c, 0x40, 0x7a,
	0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0xa0,
	0x26, 0x43, 0x38, 0x20, 0x9d, 0xae, 0x45, 0x45, 0xbe, 0xc5, 0xe9, 0x50, 0x33, 0xa1, 0x3c, 0xa3,
	0x5c, 0x2e, 0x1e, 0x64, 0x3f, 0x08, 0xc5, 0x72, 0x09, 0x38, 0x27, 0xe6, 0xe4, 0xa0, 0x88, 0x29,
	0xe9, 0xe1, 0xf4, 0xb3, 0x1e, 0xd4, 0x4f, 0x52, 0xca, 0x78, 0xd5, 0x40, 0x9c, 0xa6, 0xc4, 0x90,
	0xc4, 0x06, 0x0e, 0x44, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x17, 0xfb, 0xc6, 0x6d,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostUserAuthClient is the client API for PostUserAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostUserAuthClient interface {
	CallPostUserAuth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postUserAuthClient struct {
	cc *grpc.ClientConn
}

func NewPostUserAuthClient(cc *grpc.ClientConn) PostUserAuthClient {
	return &postUserAuthClient{cc}
}

func (c *postUserAuthClient) CallPostUserAuth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.PostUserAuth.PostUserAuth/CallPostUserAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostUserAuthServer is the server API for PostUserAuth service.
type PostUserAuthServer interface {
	CallPostUserAuth(context.Context, *Request) (*Response, error)
}

// UnimplementedPostUserAuthServer can be embedded to have forward compatible implementations.
type UnimplementedPostUserAuthServer struct {
}

func (*UnimplementedPostUserAuthServer) CallPostUserAuth(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPostUserAuth not implemented")
}

func RegisterPostUserAuthServer(s *grpc.Server, srv PostUserAuthServer) {
	s.RegisterService(&_PostUserAuth_serviceDesc, srv)
}

func _PostUserAuth_CallPostUserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostUserAuthServer).CallPostUserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.PostUserAuth.PostUserAuth/CallPostUserAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostUserAuthServer).CallPostUserAuth(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostUserAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.PostUserAuth.PostUserAuth",
	HandlerType: (*PostUserAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPostUserAuth",
			Handler:    _PostUserAuth_CallPostUserAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PostUserAuth/PostUserAuth.proto",
}
