// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetIndex/GetIndex.proto

package go_micro_srv_GetIndex

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2978efbb3e6e57ff, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2978efbb3e6e57ff, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	IndexBytes           []byte   `protobuf:"bytes,3,opt,name=IndexBytes,proto3" json:"IndexBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2978efbb3e6e57ff, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetIndexBytes() []byte {
	if m != nil {
		return m.IndexBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetIndex.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetIndex.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetIndex.Response")
}

func init() { proto.RegisterFile("proto/GetIndex/GetIndex.proto", fileDescriptor_2978efbb3e6e57ff) }

var fileDescriptor_2978efbb3e6e57ff = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0x4f, 0x2d, 0xf1, 0xcc, 0x4b, 0x49, 0xad, 0x80, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0xa2, 0xe9, 0xf9, 0x7a, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x30, 0x49,
	0x25, 0x69, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0xe2,
	0xc4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x89, 0x93, 0x8b, 0x3d, 0x28,
	0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x29, 0x82, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x55, 0x48, 0x84, 0x8b, 0xd5, 0xb5, 0xa8, 0x28, 0xbf, 0x08, 0xaa, 0x14, 0xc2, 0x11, 0x12,
	0xe3, 0x62, 0x73, 0x2d, 0x2a, 0xf2, 0x2d, 0x4e, 0x97, 0x60, 0x02, 0x0b, 0x43, 0x79, 0x42, 0x72,
	0x5c, 0x5c, 0x60, 0xab, 0x9c, 0x2a, 0x4b, 0x52, 0x8b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x78, 0x82,
	0x90, 0x44, 0x8c, 0x62, 0xb9, 0x38, 0x60, 0xae, 0x11, 0x0a, 0xe4, 0xe2, 0x71, 0x4e, 0xcc, 0xc9,
	0x81, 0xf3, 0xe5, 0xf4, 0xb0, 0xba, 0x5a, 0x0f, 0xea, 0x2a, 0x29, 0x79, 0x9c, 0xf2, 0x10, 0xa7,
	0x2a, 0x31, 0x24, 0xb1, 0x81, 0xbd, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x01, 0x6a,
	0x38, 0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetIndexClient is the client API for GetIndex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetIndexClient interface {
	CallGetIndex(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getIndexClient struct {
	cc *grpc.ClientConn
}

func NewGetIndexClient(cc *grpc.ClientConn) GetIndexClient {
	return &getIndexClient{cc}
}

func (c *getIndexClient) CallGetIndex(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.GetIndex.GetIndex/CallGetIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetIndexServer is the server API for GetIndex service.
type GetIndexServer interface {
	CallGetIndex(context.Context, *Request) (*Response, error)
}

// UnimplementedGetIndexServer can be embedded to have forward compatible implementations.
type UnimplementedGetIndexServer struct {
}

func (*UnimplementedGetIndexServer) CallGetIndex(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallGetIndex not implemented")
}

func RegisterGetIndexServer(s *grpc.Server, srv GetIndexServer) {
	s.RegisterService(&_GetIndex_serviceDesc, srv)
}

func _GetIndex_CallGetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetIndexServer).CallGetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.GetIndex.GetIndex/CallGetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetIndexServer).CallGetIndex(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetIndex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.GetIndex.GetIndex",
	HandlerType: (*GetIndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallGetIndex",
			Handler:    _GetIndex_CallGetIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetIndex/GetIndex.proto",
}
