// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetArea/GetArea.proto

package go_micro_srv_GetArea

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	// 错误码
	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	// 错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	// 地区信息数组
	Data                 []*Response_Areas `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*Response_Areas {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_Areas struct {
	// 地区iD
	Aid int32 `protobuf:"varint,1,opt,name=Aid,proto3" json:"Aid,omitempty"`
	// 地区名称
	Aname                string   `protobuf:"bytes,2,opt,name=Aname,proto3" json:"Aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Areas) Reset()         { *m = Response_Areas{} }
func (m *Response_Areas) String() string { return proto.CompactTextString(m) }
func (*Response_Areas) ProtoMessage()    {}
func (*Response_Areas) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{2, 0}
}

func (m *Response_Areas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Areas.Unmarshal(m, b)
}
func (m *Response_Areas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Areas.Marshal(b, m, deterministic)
}
func (m *Response_Areas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Areas.Merge(m, src)
}
func (m *Response_Areas) XXX_Size() int {
	return xxx_messageInfo_Response_Areas.Size(m)
}
func (m *Response_Areas) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Areas.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Areas proto.InternalMessageInfo

func (m *Response_Areas) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *Response_Areas) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetArea.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetArea.Response")
	proto.RegisterType((*Response_Areas)(nil), "go.micro.srv.GetArea.Response.Areas")
}

func init() { proto.RegisterFile("proto/GetArea/GetArea.proto", fileDescriptor_2c643115bb4a9c45) }

var fileDescriptor_2c643115bb4a9c45 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0xad, 0xb5, 0xaf, 0xef, 0x5d, 0x17, 0x09, 0x0f, 0x29, 0xef, 0xa1, 0x94, 0xe0, 0xd0,
	0x29, 0x85, 0xba, 0xb8, 0x16, 0x2c, 0x0e, 0xe2, 0x92, 0xc1, 0x3d, 0xea, 0xa5, 0x74, 0x68, 0x53,
	0xef, 0x8d, 0x82, 0xbf, 0xc7, 0x3f, 0x2a, 0x49, 0xd3, 0x4d, 0x9d, 0x72, 0xbe, 0x9b, 0xe4, 0x9c,
	0x93, 0xc0, 0x71, 0x26, 0xeb, 0x6c, 0xfd, 0x80, 0xae, 0x25, 0x34, 0xeb, 0xaa, 0xc2, 0x54, 0xec,
	0x7b, 0xab, 0xc6, 0xe1, 0x95, 0xac, 0x62, 0xfa, 0x54, 0x71, 0x4f, 0x1e, 0x21, 0x7f, 0x42, 0x66,
	0xd3, 0xa3, 0xb8, 0x80, 0x94, 0xcd, 0x57, 0x91, 0x94, 0x49, 0xb5, 0xd3, 0x5e, 0xca, 0x1d, 0xe4,
	0x1a, 0xdf, 0x3f, 0x90, 0x9d, 0xfc, 0x4e, 0x60, 0xab, 0x91, 0x67, 0x3b, 0x31, 0x8a, 0x3d, 0x64,
	0x1d, 0x91, 0xa5, 0x78, 0x76, 0x01, 0x71, 0x09, 0x9b, 0x8e, 0x68, 0xe4, 0xbe, 0x38, 0x0d, 0xe3,
	0x48, 0xe2, 0x0e, 0xce, 0xee, 0x8d, 0x33, 0x45, 0x5a, 0xa6, 0xd5, 0x79, 0x73, 0xa3, 0x7e, 0xeb,
	0xa1, 0x56, 0x6f, 0xe5, 0x89, 0x75, 0xb8, 0x71, 0xa8, 0x21, 0x0b, 0xe8, 0xab, 0xb5, 0xc3, 0x5b,
	0x88, 0xcb, 0xb4, 0x97, 0xbe, 0x42, 0x3b, 0x99, 0x11, 0x63, 0xd6, 0x02, 0xcd, 0x33, 0xe4, 0xd1,
	0x50, 0x3c, 0xc2, 0x36, 0x4a, 0x16, 0x57, 0x7f, 0x65, 0x86, 0xb7, 0x1d, 0xae, 0xff, 0xaf, 0x24,
	0x4f, 0x5e, 0x36, 0xe1, 0x0b, 0x6f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x8e, 0xdd, 0xc9,
	0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetAreaClient is the client API for GetArea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetAreaClient interface {
	// 获取地区信息服务
	GetAreas(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getAreaClient struct {
	cc *grpc.ClientConn
}

func NewGetAreaClient(cc *grpc.ClientConn) GetAreaClient {
	return &getAreaClient{cc}
}

func (c *getAreaClient) GetAreas(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.GetArea.GetArea/GetAreas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAreaServer is the server API for GetArea service.
type GetAreaServer interface {
	// 获取地区信息服务
	GetAreas(context.Context, *Request) (*Response, error)
}

// UnimplementedGetAreaServer can be embedded to have forward compatible implementations.
type UnimplementedGetAreaServer struct {
}

func (*UnimplementedGetAreaServer) GetAreas(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAreas not implemented")
}

func RegisterGetAreaServer(s *grpc.Server, srv GetAreaServer) {
	s.RegisterService(&_GetArea_serviceDesc, srv)
}

func _GetArea_GetAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAreaServer).GetAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.GetArea.GetArea/GetAreas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAreaServer).GetAreas(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetArea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.GetArea.GetArea",
	HandlerType: (*GetAreaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAreas",
			Handler:    _GetArea_GetAreas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetArea/GetArea.proto",
}
