// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PostSession/PostSession.proto

package go_micro_srv_PostSession

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostSession service

type PostSessionService interface {
	CallPostSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postSessionService struct {
	c    client.Client
	name string
}

func NewPostSessionService(name string, c client.Client) PostSessionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostSession"
	}
	return &postSessionService{
		c:    c,
		name: name,
	}
}

func (c *postSessionService) CallPostSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostSession.CallPostSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostSession service

type PostSessionHandler interface {
	CallPostSession(context.Context, *Request, *Response) error
}

func RegisterPostSessionHandler(s server.Server, hdlr PostSessionHandler, opts ...server.HandlerOption) error {
	type postSession interface {
		CallPostSession(ctx context.Context, in *Request, out *Response) error
	}
	type PostSession struct {
		postSession
	}
	h := &postSessionHandler{hdlr}
	return s.Handle(s.NewHandler(&PostSession{h}, opts...))
}

type postSessionHandler struct {
	PostSessionHandler
}

func (h *postSessionHandler) CallPostSession(ctx context.Context, in *Request, out *Response) error {
	return h.PostSessionHandler.CallPostSession(ctx, in, out)
}
