// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/PostSession/PostSession.proto

package go_micro_srv_PostSession

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fed8c506421ecf, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fed8c506421ecf, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fed8c506421ecf, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.PostSession.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostSession.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostSession.Response")
}

func init() {
	proto.RegisterFile("proto/PostSession/PostSession.proto", fileDescriptor_c9fed8c506421ecf)
}

var fileDescriptor_c9fed8c506421ecf = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0x87, 0x7d, 0x3e, 0x7c, 0xef, 0xf5, 0x1c, 0x94, 0x20, 0x12, 0xaa, 0x83, 0xc6, 0xc5, 0x29,
	0x82, 0xce, 0x4e, 0xda, 0xc1, 0xa1, 0x50, 0x2a, 0x38, 0xb8, 0xa5, 0x7a, 0x94, 0x40, 0xed, 0xd5,
	0xbb, 0xaa, 0xf8, 0xdf, 0x4b, 0xd3, 0xa0, 0x59, 0x7c, 0xdb, 0x7d, 0xf7, 0xe5, 0xc2, 0xfd, 0x0e,
	0x2e, 0x06, 0xa6, 0x91, 0xae, 0x2a, 0x92, 0xf1, 0x11, 0x45, 0x3c, 0xf5, 0x69, 0x6d, 0x83, 0x55,
	0xba, 0x25, 0xfb, 0xe6, 0x5f, 0x98, 0xac, 0xf0, 0xa7, 0x4d, 0xbc, 0x39, 0x81, 0x75, 0x89, 0x22,
	0xae, 0x45, 0x75, 0x08, 0x4b, 0x71, 0xdf, 0x7a, 0x71, 0xb6, 0xb8, 0xcc, 0xea, 0xa9, 0x34, 0xb7,
	0xb0, 0xae, 0xf1, 0xfd, 0x03, 0x65, 0x54, 0xc7, 0xb0, 0x2a, 0xa9, 0xf1, 0x1d, 0x46, 0x1f, 0x49,
	0xe5, 0xb0, 0xa9, 0x9c, 0xc8, 0x17, 0xf1, 0xab, 0xde, 0x0d, 0xe6, 0x97, 0xcd, 0x13, 0x6c, 0x6a,
	0x94, 0x81, 0x7a, 0x41, 0x75, 0x04, 0x7b, 0x05, 0x33, 0x71, 0x1c, 0x9f, 0x61, 0xfa, 0xb5, 0x60,
	0x2e, 0xa5, 0x8d, 0xb3, 0x91, 0xd4, 0x29, 0x64, 0x71, 0xc1, 0x87, 0x7b, 0xbd, 0x0c, 0xea, 0xaf,
	0x71, 0xed, 0x61, 0x3f, 0x89, 0xa0, 0x9e, 0xe1, 0xe0, 0xce, 0x75, 0x5d, 0xda, 0x3a, 0xb7, 0xff,
	0x05, 0xb6, 0x31, 0x50, 0x6e, 0xb6, 0x3d, 0x99, 0x97, 0x36, 0x3b, 0xcd, 0x2a, 0xdc, 0xef, 0xe6,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x50, 0x24, 0x55, 0x66, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostSessionClient is the client API for PostSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostSessionClient interface {
	CallPostSession(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postSessionClient struct {
	cc *grpc.ClientConn
}

func NewPostSessionClient(cc *grpc.ClientConn) PostSessionClient {
	return &postSessionClient{cc}
}

func (c *postSessionClient) CallPostSession(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.PostSession.PostSession/CallPostSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSessionServer is the server API for PostSession service.
type PostSessionServer interface {
	CallPostSession(context.Context, *Request) (*Response, error)
}

// UnimplementedPostSessionServer can be embedded to have forward compatible implementations.
type UnimplementedPostSessionServer struct {
}

func (*UnimplementedPostSessionServer) CallPostSession(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPostSession not implemented")
}

func RegisterPostSessionServer(s *grpc.Server, srv PostSessionServer) {
	s.RegisterService(&_PostSession_serviceDesc, srv)
}

func _PostSession_CallPostSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSessionServer).CallPostSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.PostSession.PostSession/CallPostSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSessionServer).CallPostSession(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostSession_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.PostSession.PostSession",
	HandlerType: (*PostSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPostSession",
			Handler:    _PostSession_CallPostSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PostSession/PostSession.proto",
}
