// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/DeleteSession/DeleteSession.proto

package go_micro_srv_DeleteSession

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf54c5a46d2adc5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	// 退出用户身份
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf54c5a46d2adc5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf54c5a46d2adc5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.DeleteSession.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.DeleteSession.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.DeleteSession.Response")
}

func init() {
	proto.RegisterFile("proto/DeleteSession/DeleteSession.proto", fileDescriptor_6bf54c5a46d2adc5)
}

var fileDescriptor_6bf54c5a46d2adc5 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0x0d, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x43,
	0xe5, 0xe9, 0x81, 0x55, 0x08, 0x49, 0xa5, 0xe7, 0xeb, 0xe5, 0x66, 0x26, 0x17, 0xe5, 0xeb, 0x15,
	0x17, 0x95, 0xe9, 0xa1, 0xa8, 0x50, 0x92, 0xe6, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x15, 0x12, 0xe0, 0x62, 0x2e, 0x4e, 0xac, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31,
	0x95, 0xd4, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0x8b,
	0x21, 0x5a, 0x3c, 0x5d, 0xa0, 0x4a, 0x10, 0x02, 0x4a, 0x16, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x50, 0x55, 0x10,
	0x8e, 0x90, 0x18, 0x17, 0x9b, 0x6b, 0x51, 0x91, 0x6f, 0x71, 0xba, 0x04, 0x13, 0x58, 0x18, 0xca,
	0x33, 0x2a, 0xe4, 0xe2, 0x45, 0x71, 0x90, 0x50, 0x02, 0x97, 0xa0, 0x73, 0x62, 0x4e, 0x0e, 0xaa,
	0xa0, 0xb2, 0x1e, 0x6e, 0x2f, 0xe8, 0x41, 0x9d, 0x28, 0xa5, 0x82, 0x5f, 0x11, 0xc4, 0x79, 0x4a,
	0x0c, 0x49, 0x6c, 0xe0, 0x50, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xc8, 0x3f, 0x82,
	0x40, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeleteSessionClient is the client API for DeleteSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeleteSessionClient interface {
	CallDeleteSession(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type deleteSessionClient struct {
	cc *grpc.ClientConn
}

func NewDeleteSessionClient(cc *grpc.ClientConn) DeleteSessionClient {
	return &deleteSessionClient{cc}
}

func (c *deleteSessionClient) CallDeleteSession(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.DeleteSession.DeleteSession/CallDeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteSessionServer is the server API for DeleteSession service.
type DeleteSessionServer interface {
	CallDeleteSession(context.Context, *Request) (*Response, error)
}

// UnimplementedDeleteSessionServer can be embedded to have forward compatible implementations.
type UnimplementedDeleteSessionServer struct {
}

func (*UnimplementedDeleteSessionServer) CallDeleteSession(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallDeleteSession not implemented")
}

func RegisterDeleteSessionServer(s *grpc.Server, srv DeleteSessionServer) {
	s.RegisterService(&_DeleteSession_serviceDesc, srv)
}

func _DeleteSession_CallDeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeleteSessionServer).CallDeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.DeleteSession.DeleteSession/CallDeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeleteSessionServer).CallDeleteSession(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeleteSession_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.DeleteSession.DeleteSession",
	HandlerType: (*DeleteSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallDeleteSession",
			Handler:    _DeleteSession_CallDeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/DeleteSession/DeleteSession.proto",
}
