// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/DeleteSession/DeleteSession.proto

package go_micro_srv_DeleteSession

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DeleteSession service

type DeleteSessionService interface {
	CallDeleteSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type deleteSessionService struct {
	c    client.Client
	name string
}

func NewDeleteSessionService(name string, c client.Client) DeleteSessionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.DeleteSession"
	}
	return &deleteSessionService{
		c:    c,
		name: name,
	}
}

func (c *deleteSessionService) CallDeleteSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DeleteSession.CallDeleteSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeleteSession service

type DeleteSessionHandler interface {
	CallDeleteSession(context.Context, *Request, *Response) error
}

func RegisterDeleteSessionHandler(s server.Server, hdlr DeleteSessionHandler, opts ...server.HandlerOption) error {
	type deleteSession interface {
		CallDeleteSession(ctx context.Context, in *Request, out *Response) error
	}
	type DeleteSession struct {
		deleteSession
	}
	h := &deleteSessionHandler{hdlr}
	return s.Handle(s.NewHandler(&DeleteSession{h}, opts...))
}

type deleteSessionHandler struct {
	DeleteSessionHandler
}

func (h *deleteSessionHandler) CallDeleteSession(ctx context.Context, in *Request, out *Response) error {
	return h.DeleteSessionHandler.CallDeleteSession(ctx, in, out)
}
