// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PostHousesImage/PostHousesImage.proto

package go_micro_srv_PostHousesImage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostHousesImage service

type PostHousesImageService interface {
	CallPostHousesImage(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postHousesImageService struct {
	c    client.Client
	name string
}

func NewPostHousesImageService(name string, c client.Client) PostHousesImageService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostHousesImage"
	}
	return &postHousesImageService{
		c:    c,
		name: name,
	}
}

func (c *postHousesImageService) CallPostHousesImage(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostHousesImage.CallPostHousesImage", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostHousesImage service

type PostHousesImageHandler interface {
	CallPostHousesImage(context.Context, *Request, *Response) error
}

func RegisterPostHousesImageHandler(s server.Server, hdlr PostHousesImageHandler, opts ...server.HandlerOption) error {
	type postHousesImage interface {
		CallPostHousesImage(ctx context.Context, in *Request, out *Response) error
	}
	type PostHousesImage struct {
		postHousesImage
	}
	h := &postHousesImageHandler{hdlr}
	return s.Handle(s.NewHandler(&PostHousesImage{h}, opts...))
}

type postHousesImageHandler struct {
	PostHousesImageHandler
}

func (h *postHousesImageHandler) CallPostHousesImage(ctx context.Context, in *Request, out *Response) error {
	return h.PostHousesImageHandler.CallPostHousesImage(ctx, in, out)
}
