// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/PostHousesImage/PostHousesImage.proto

package go_micro_srv_PostHousesImage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_61784daeffe8f8f2, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	// 用户身份凭证
	SessionID string `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	// 图片二进制数据
	Image []byte `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	// 图片所属房屋id
	HouseID string `protobuf:"bytes,3,opt,name=HouseID,proto3" json:"HouseID,omitempty"`
	// 图片大小
	FileSize int64 `protobuf:"zigzag64,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	// 图片名称
	FileName             string   `protobuf:"bytes,5,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_61784daeffe8f8f2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Request) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Request) GetHouseID() string {
	if m != nil {
		return m.HouseID
	}
	return ""
}

func (m *Request) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Request) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type Response struct {
	Error  string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 图片位置
	Filed                string   `protobuf:"bytes,3,opt,name=Filed,proto3" json:"Filed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_61784daeffe8f8f2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetFiled() string {
	if m != nil {
		return m.Filed
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.PostHousesImage.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostHousesImage.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostHousesImage.Response")
}

func init() {
	proto.RegisterFile("proto/PostHousesImage/PostHousesImage.proto", fileDescriptor_61784daeffe8f8f2)
}

var fileDescriptor_61784daeffe8f8f2 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x5d, 0x6b, 0x7f, 0x32, 0x08, 0xca, 0x2a, 0xb2, 0xd4, 0x5e, 0x84, 0x80, 0x12, 0x10,
	0x56, 0xd0, 0x47, 0xb0, 0x15, 0x73, 0xd1, 0x22, 0xdb, 0x27, 0x58, 0x75, 0x0c, 0x81, 0xa4, 0x53,
	0x77, 0x52, 0xa1, 0xbe, 0x84, 0xaf, 0x2c, 0xd9, 0x6c, 0x2b, 0xe4, 0x42, 0xef, 0xf6, 0x9b, 0x3d,
	0x33, 0x73, 0x38, 0x03, 0x37, 0x6b, 0x47, 0x35, 0xdd, 0x3e, 0x13, 0xd7, 0x4f, 0xb4, 0x61, 0xe4,
	0xac, 0xb2, 0x39, 0x76, 0x59, 0x7b, 0x95, 0x9c, 0xe4, 0xa4, 0xab, 0xe2, 0xd5, 0x91, 0x66, 0xf7,
	0xa9, 0x3b, 0x9a, 0xe4, 0x12, 0x86, 0x73, 0x64, 0xb6, 0x39, 0xca, 0x53, 0xe8, 0xb1, 0xdd, 0x2a,
	0x11, 0x8b, 0x34, 0x32, 0xcd, 0x33, 0xf9, 0x16, 0x30, 0x34, 0xf8, 0xb1, 0x41, 0xae, 0xe5, 0x04,
	0xa2, 0x25, 0x32, 0x17, 0xb4, 0xca, 0xa6, 0x41, 0xf3, 0x5b, 0x90, 0xe7, 0xd0, 0xf7, 0xf3, 0xd4,
	0x61, 0x2c, 0xd2, 0x63, 0xd3, 0x82, 0x54, 0x30, 0xf4, 0xbb, 0xb2, 0xa9, 0xea, 0xf9, 0x8e, 0x1d,
	0xca, 0x31, 0x8c, 0x1e, 0x8b, 0x12, 0x97, 0xc5, 0x17, 0xaa, 0xa3, 0x58, 0xa4, 0xd2, 0xec, 0x79,
	0xf7, 0xb7, 0xb0, 0x15, 0xaa, 0xbe, 0x6f, 0xdb, 0x73, 0xb2, 0x80, 0x91, 0x41, 0x5e, 0xd3, 0x8a,
	0xb1, 0xd9, 0x39, 0x73, 0x8e, 0x5c, 0x70, 0xd3, 0x82, 0xbc, 0x80, 0xc1, 0xcc, 0xb9, 0x39, 0xe7,
	0xde, 0x4a, 0x64, 0x02, 0x35, 0xea, 0x66, 0xca, 0x5b, 0x70, 0xd2, 0xc2, 0xdd, 0x16, 0x4e, 0x3a,
	0x89, 0xc8, 0x77, 0x38, 0x7b, 0xb0, 0x65, 0xd9, 0x2d, 0x5f, 0xe9, 0xbf, 0x72, 0xd4, 0x21, 0xa6,
	0xf1, 0xf5, 0x7f, 0xb2, 0xd6, 0x7c, 0x72, 0xf0, 0x32, 0xf0, 0xe7, 0xb9, 0xff, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xa1, 0x10, 0xbb, 0x96, 0xcd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostHousesImageClient is the client API for PostHousesImage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostHousesImageClient interface {
	CallPostHousesImage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postHousesImageClient struct {
	cc *grpc.ClientConn
}

func NewPostHousesImageClient(cc *grpc.ClientConn) PostHousesImageClient {
	return &postHousesImageClient{cc}
}

func (c *postHousesImageClient) CallPostHousesImage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.PostHousesImage.PostHousesImage/CallPostHousesImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostHousesImageServer is the server API for PostHousesImage service.
type PostHousesImageServer interface {
	CallPostHousesImage(context.Context, *Request) (*Response, error)
}

// UnimplementedPostHousesImageServer can be embedded to have forward compatible implementations.
type UnimplementedPostHousesImageServer struct {
}

func (*UnimplementedPostHousesImageServer) CallPostHousesImage(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPostHousesImage not implemented")
}

func RegisterPostHousesImageServer(s *grpc.Server, srv PostHousesImageServer) {
	s.RegisterService(&_PostHousesImage_serviceDesc, srv)
}

func _PostHousesImage_CallPostHousesImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostHousesImageServer).CallPostHousesImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.PostHousesImage.PostHousesImage/CallPostHousesImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostHousesImageServer).CallPostHousesImage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostHousesImage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.PostHousesImage.PostHousesImage",
	HandlerType: (*PostHousesImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPostHousesImage",
			Handler:    _PostHousesImage_CallPostHousesImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PostHousesImage/PostHousesImage.proto",
}
