// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetImageCd/GetImageCd.proto

package go_micro_srv_GetImageCd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Error  string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	// 图片对象的零件
	Pix                  []byte          `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64           `protobuf:"zigzag64,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"zigzag64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"zigzag64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
}

func init() { proto.RegisterFile("proto/GetImageCd/GetImageCd.proto", fileDescriptor_208a871f55559f63) }

var fileDescriptor_208a871f55559f63 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xf6, 0x4b, 0x93, 0xea, 0x58, 0x44, 0x06, 0xd1, 0xa5, 0x22, 0xa4, 0xf1, 0x60, 0x4e,
	0x2b, 0xd4, 0x93, 0xe7, 0x52, 0xc4, 0x43, 0xa1, 0xac, 0x88, 0xed, 0x71, 0x35, 0x43, 0x58, 0x68,
	0xb2, 0x75, 0x37, 0x95, 0xf8, 0xe3, 0x05, 0xd9, 0x35, 0xd2, 0x5e, 0x54, 0xbc, 0xbd, 0x37, 0x6f,
	0xde, 0xce, 0xbc, 0x1d, 0x18, 0xad, 0xad, 0x69, 0xcc, 0xd5, 0x2d, 0x35, 0x77, 0x95, 0x2a, 0x69,
	0x52, 0xec, 0x40, 0x11, 0x34, 0x3c, 0x2d, 0x8d, 0xa8, 0xf4, 0xb3, 0x35, 0xc2, 0xd9, 0x57, 0xb1,
	0x95, 0xb3, 0x33, 0xe8, 0xcf, 0xc8, 0x39, 0x55, 0x12, 0x1e, 0x41, 0xe4, 0xd4, 0x1b, 0x67, 0x29,
	0xcb, 0xf7, 0xa5, 0x87, 0xd9, 0x39, 0xf4, 0x25, 0xbd, 0x6c, 0xc8, 0x35, 0x88, 0xd0, 0x7b, 0xd8,
	0xe8, 0xa2, 0x53, 0x03, 0xce, 0xde, 0x19, 0xec, 0x49, 0x72, 0x6b, 0x53, 0x3b, 0xc2, 0x63, 0x88,
	0xa7, 0xd6, 0x1a, 0xdb, 0x75, 0x7c, 0x12, 0x3c, 0x81, 0x64, 0x6a, 0x6d, 0xe5, 0x4a, 0xfe, 0x3f,
	0x94, 0x3b, 0xe6, 0x67, 0xcd, 0x75, 0xcb, 0xa3, 0x94, 0xe5, 0x03, 0xe9, 0xa1, 0xef, 0xbc, 0x6f,
	0xac, 0x2e, 0x88, 0xf7, 0x52, 0x96, 0xa3, 0xec, 0x18, 0xde, 0x40, 0x34, 0xd3, 0x35, 0x8f, 0x53,
	0x96, 0x1f, 0x8c, 0x2f, 0xc5, 0x37, 0x39, 0xc4, 0xd7, 0x1e, 0x62, 0x6e, 0x74, 0xdd, 0x48, 0xef,
	0x09, 0x56, 0xd5, 0xf2, 0xe4, 0xaf, 0x56, 0xd5, 0x0e, 0x2f, 0x20, 0x0e, 0x0c, 0x07, 0xc0, 0x16,
	0x21, 0x12, 0x4a, 0xb6, 0xf0, 0x6c, 0x19, 0x92, 0xa0, 0x64, 0xcb, 0x31, 0x01, 0x6c, 0x9f, 0xc1,
	0x47, 0x38, 0x9c, 0xa8, 0xd5, 0x6a, 0xa7, 0x92, 0xfe, 0x30, 0x32, 0xfc, 0xea, 0x70, 0xf4, 0xeb,
	0x52, 0xd9, 0xbf, 0xa7, 0x24, 0x9c, 0xf0, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0xda, 0x35, 0x6d,
	0x49, 0xe7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetImageCdClient is the client API for GetImageCd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetImageCdClient interface {
	CallGetImageCd(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getImageCdClient struct {
	cc *grpc.ClientConn
}

func NewGetImageCdClient(cc *grpc.ClientConn) GetImageCdClient {
	return &getImageCdClient{cc}
}

func (c *getImageCdClient) CallGetImageCd(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.GetImageCd.GetImageCd/CallGetImageCd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetImageCdServer is the server API for GetImageCd service.
type GetImageCdServer interface {
	CallGetImageCd(context.Context, *Request) (*Response, error)
}

// UnimplementedGetImageCdServer can be embedded to have forward compatible implementations.
type UnimplementedGetImageCdServer struct {
}

func (*UnimplementedGetImageCdServer) CallGetImageCd(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallGetImageCd not implemented")
}

func RegisterGetImageCdServer(s *grpc.Server, srv GetImageCdServer) {
	s.RegisterService(&_GetImageCd_serviceDesc, srv)
}

func _GetImageCd_CallGetImageCd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetImageCdServer).CallGetImageCd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.GetImageCd.GetImageCd/CallGetImageCd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetImageCdServer).CallGetImageCd(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetImageCd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.GetImageCd.GetImageCd",
	HandlerType: (*GetImageCdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallGetImageCd",
			Handler:    _GetImageCd_CallGetImageCd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetImageCd/GetImageCd.proto",
}
