// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetUserInfo/GetUserInfo.proto

package go_micro_srv_GetUserInfo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2e9953d843afed4, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	// 通过sessionID获取用户身份
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2e9953d843afed4, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type Response struct {
	// 错误码
	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 用户id
	UserID int64 `protobuf:"zigzag64,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// 用户名
	Name string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	// 用户手机号
	Mobile string `protobuf:"bytes,5,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// 用户真实姓名
	RealName string `protobuf:"bytes,6,opt,name=RealName,proto3" json:"RealName,omitempty"`
	// 身份证号
	IDCard string `protobuf:"bytes,7,opt,name=IDCard,proto3" json:"IDCard,omitempty"`
	// 头像链接
	AvatarUrl            string   `protobuf:"bytes,8,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2e9953d843afed4, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Response) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Response) GetIDCard() string {
	if m != nil {
		return m.IDCard
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetUserInfo.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetUserInfo.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetUserInfo.Response")
}

func init() {
	proto.RegisterFile("proto/GetUserInfo/GetUserInfo.proto", fileDescriptor_c2e9953d843afed4)
}

var fileDescriptor_c2e9953d843afed4 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x09, 0x6d, 0x93, 0xf6, 0x18, 0x40, 0x16, 0x42, 0x56, 0x61, 0x28, 0x61, 0xa0, 0x93,
	0x91, 0xe0, 0x09, 0x50, 0x53, 0xa1, 0x0c, 0x61, 0x08, 0xea, 0xc2, 0xe6, 0xc2, 0x11, 0x45, 0x4a,
	0xe3, 0x72, 0x17, 0x2a, 0xf1, 0x92, 0x3c, 0x13, 0xf2, 0x1f, 0x95, 0x30, 0xc0, 0x76, 0xdf, 0x77,
	0xbf, 0xb3, 0x7d, 0x9f, 0xe1, 0x6a, 0x4b, 0xa6, 0x33, 0x37, 0x0f, 0xd8, 0xad, 0x18, 0x29, 0x6f,
	0xdf, 0x7e, 0xd5, 0xca, 0x75, 0x85, 0xac, 0x8c, 0xda, 0xd4, 0x2f, 0x64, 0x14, 0xd3, 0x4e, 0xf5,
	0xfa, 0xe9, 0x39, 0x24, 0x05, 0x32, 0xeb, 0x0a, 0xc5, 0x09, 0x0c, 0x58, 0x7f, 0xca, 0x68, 0x16,
	0xcd, 0x27, 0xa5, 0x2d, 0xd3, 0x6b, 0x48, 0x4a, 0x7c, 0xff, 0x40, 0xee, 0xc4, 0x05, 0x4c, 0x9e,
	0x90, 0xb9, 0x36, 0x6d, 0x9e, 0x05, 0xe4, 0xc7, 0x48, 0xbf, 0x22, 0x18, 0x97, 0xc8, 0x5b, 0xd3,
	0x32, 0x8a, 0x53, 0x18, 0x2d, 0x89, 0x0c, 0x05, 0xcc, 0x0b, 0x71, 0x06, 0xf1, 0x92, 0xa8, 0xe0,
	0x4a, 0x1e, 0x3a, 0x3b, 0x28, 0xeb, 0xbb, 0xc7, 0x64, 0x72, 0x30, 0x8b, 0xe6, 0xa2, 0x0c, 0x4a,
	0x08, 0x18, 0x3e, 0xea, 0x0d, 0xca, 0xa1, 0xa3, 0x5d, 0x6d, 0xd9, 0xc2, 0xac, 0xeb, 0x06, 0xe5,
	0xc8, 0x9f, 0xe1, 0x95, 0x98, 0xda, 0xdb, 0x75, 0xe3, 0xf8, 0xd8, 0x75, 0xf6, 0xda, 0xce, 0xe4,
	0xd9, 0x42, 0xd3, 0xab, 0x4c, 0xfc, 0x8c, 0x57, 0x76, 0xa1, 0xfb, 0x9d, 0xee, 0x34, 0xad, 0xa8,
	0x91, 0x63, 0xbf, 0xd0, 0xde, 0xb8, 0xad, 0xe1, 0xa8, 0x97, 0x92, 0x78, 0x86, 0xe3, 0x85, 0x6e,
	0x9a, 0xbe, 0x75, 0xa9, 0xfe, 0xca, 0x54, 0x85, 0xcc, 0xa6, 0xe9, 0x7f, 0x88, 0x0f, 0x2b, 0x3d,
	0x58, 0xc7, 0xee, 0x8b, 0xee, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa3, 0x65, 0x01, 0xc9,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetUserInfoClient is the client API for GetUserInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUserInfoClient interface {
	CallGetUserInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getUserInfoClient struct {
	cc *grpc.ClientConn
}

func NewGetUserInfoClient(cc *grpc.ClientConn) GetUserInfoClient {
	return &getUserInfoClient{cc}
}

func (c *getUserInfoClient) CallGetUserInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.GetUserInfo.GetUserInfo/CallGetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserInfoServer is the server API for GetUserInfo service.
type GetUserInfoServer interface {
	CallGetUserInfo(context.Context, *Request) (*Response, error)
}

// UnimplementedGetUserInfoServer can be embedded to have forward compatible implementations.
type UnimplementedGetUserInfoServer struct {
}

func (*UnimplementedGetUserInfoServer) CallGetUserInfo(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallGetUserInfo not implemented")
}

func RegisterGetUserInfoServer(s *grpc.Server, srv GetUserInfoServer) {
	s.RegisterService(&_GetUserInfo_serviceDesc, srv)
}

func _GetUserInfo_CallGetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserInfoServer).CallGetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.GetUserInfo.GetUserInfo/CallGetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserInfoServer).CallGetUserInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUserInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.GetUserInfo.GetUserInfo",
	HandlerType: (*GetUserInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallGetUserInfo",
			Handler:    _GetUserInfo_CallGetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetUserInfo/GetUserInfo.proto",
}
