// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/PostAvatar/PostAvatar.proto

package go_micro_srv_PostAvatar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5d039b6e6ae59d9, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	// 图片的二进制数据
	Avatar []byte `protobuf:"bytes,1,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	// 上传者凭证
	SessionID string `protobuf:"bytes,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	// 文件拓展名
	FileExt string `protobuf:"bytes,3,opt,name=FileExt,proto3" json:"FileExt,omitempty"`
	// 文件大小
	FileSize             int64    `protobuf:"zigzag64,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5d039b6e6ae59d9, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Request) GetFileExt() string {
	if m != nil {
		return m.FileExt
	}
	return ""
}

func (m *Request) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type Response struct {
	// 错误码
	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 头像图片地址
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5d039b6e6ae59d9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.PostAvatar.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostAvatar.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostAvatar.Response")
}

func init() { proto.RegisterFile("proto/PostAvatar/PostAvatar.proto", fileDescriptor_a5d039b6e6ae59d9) }

var fileDescriptor_a5d039b6e6ae59d9 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x5d, 0xab, 0xdd, 0x76, 0x10, 0x91, 0x41, 0x34, 0x54, 0x0f, 0xdb, 0x3d, 0xf5, 0x14,
	0x41, 0x7f, 0x81, 0xe8, 0x0a, 0x1e, 0x0a, 0x92, 0xa2, 0x9e, 0xa3, 0x0c, 0xcb, 0xc2, 0xda, 0xd4,
	0x99, 0xb4, 0xa8, 0xbf, 0x5e, 0x36, 0x1b, 0x4d, 0x2f, 0x7a, 0x9b, 0xf7, 0x5e, 0x86, 0xf9, 0xf2,
	0x60, 0xba, 0x62, 0xe7, 0xdd, 0xc5, 0x83, 0x13, 0x7f, 0xbd, 0xb1, 0xde, 0xf2, 0xd6, 0xa8, 0x43,
	0x86, 0xa7, 0xb5, 0xd3, 0x6f, 0xcd, 0x2b, 0x3b, 0x2d, 0xbc, 0xd1, 0x29, 0x2e, 0xcf, 0x20, 0x9f,
	0x93, 0x88, 0xad, 0x09, 0x8f, 0x60, 0x20, 0xf6, 0x53, 0x65, 0x45, 0x36, 0x1b, 0x9b, 0x6e, 0x2c,
	0xd7, 0x90, 0x1b, 0x7a, 0x5f, 0x93, 0x78, 0x3c, 0x81, 0x61, 0xbf, 0x11, 0xf2, 0x03, 0x13, 0x15,
	0x9e, 0xc3, 0x78, 0x41, 0x22, 0x8d, 0x5b, 0xde, 0xdf, 0xaa, 0xdd, 0xb0, 0x9a, 0x0c, 0x54, 0x90,
	0xdf, 0x35, 0x2d, 0x55, 0x1f, 0x5e, 0x0d, 0x42, 0xf6, 0x23, 0x71, 0x02, 0xa3, 0x6e, 0x5c, 0x34,
	0x5f, 0xa4, 0xf6, 0x8a, 0x6c, 0x86, 0xe6, 0x57, 0x97, 0x4f, 0x30, 0x32, 0x24, 0x2b, 0xb7, 0x14,
	0xc2, 0x63, 0xd8, 0xaf, 0x98, 0x1d, 0x47, 0xac, 0x5e, 0x74, 0x34, 0x15, 0xf3, 0x5c, 0xea, 0x78,
	0x32, 0xaa, 0x8e, 0xa6, 0xe7, 0x7a, 0xe4, 0x36, 0x5e, 0x4c, 0xc6, 0x25, 0x01, 0xa4, 0x9f, 0xe3,
	0x33, 0x1c, 0xde, 0xd8, 0xb6, 0xdd, 0x72, 0x0a, 0xfd, 0x47, 0x4b, 0x3a, 0xb6, 0x30, 0x99, 0xfe,
	0xf3, 0xa2, 0x07, 0x2e, 0x77, 0x5e, 0x86, 0xa1, 0xf2, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0xd3, 0x00, 0xab, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostAvatarClient is the client API for PostAvatar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostAvatarClient interface {
	CallPostAvatar(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postAvatarClient struct {
	cc *grpc.ClientConn
}

func NewPostAvatarClient(cc *grpc.ClientConn) PostAvatarClient {
	return &postAvatarClient{cc}
}

func (c *postAvatarClient) CallPostAvatar(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.PostAvatar.PostAvatar/CallPostAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostAvatarServer is the server API for PostAvatar service.
type PostAvatarServer interface {
	CallPostAvatar(context.Context, *Request) (*Response, error)
}

// UnimplementedPostAvatarServer can be embedded to have forward compatible implementations.
type UnimplementedPostAvatarServer struct {
}

func (*UnimplementedPostAvatarServer) CallPostAvatar(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPostAvatar not implemented")
}

func RegisterPostAvatarServer(s *grpc.Server, srv PostAvatarServer) {
	s.RegisterService(&_PostAvatar_serviceDesc, srv)
}

func _PostAvatar_CallPostAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAvatarServer).CallPostAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.PostAvatar.PostAvatar/CallPostAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAvatarServer).CallPostAvatar(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostAvatar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.PostAvatar.PostAvatar",
	HandlerType: (*PostAvatarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPostAvatar",
			Handler:    _PostAvatar_CallPostAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PostAvatar/PostAvatar.proto",
}
