// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/PostReg/PostReg.proto

package go_micro_srv_PostReg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_60a51312e9467d33, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SmsCode              string   `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_60a51312e9467d33, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_60a51312e9467d33, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.PostReg.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostReg.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostReg.Response")
}

func init() { proto.RegisterFile("proto/PostReg/PostReg.proto", fileDescriptor_60a51312e9467d33) }

var fileDescriptor_60a51312e9467d33 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xad, 0xc5, 0xa6, 0x1d, 0x2f, 0x32, 0x14, 0x09, 0xad, 0x8a, 0xe4, 0xe4, 0x69, 0x05,
	0x7d, 0x84, 0xda, 0x83, 0x87, 0x48, 0xd9, 0x82, 0xe2, 0x71, 0x6b, 0x87, 0x25, 0x90, 0x76, 0xea,
	0x4c, 0x54, 0x7c, 0x7b, 0xe9, 0x66, 0xa2, 0x17, 0x7b, 0xda, 0xfd, 0xe6, 0x83, 0x7f, 0xf7, 0x1f,
	0x98, 0xee, 0x84, 0x1b, 0xbe, 0x5d, 0xb0, 0x36, 0x9e, 0x62, 0x77, 0xba, 0x34, 0xc5, 0x71, 0x64,
	0xb7, 0xa9, 0xde, 0x84, 0x9d, 0xca, 0xa7, 0x33, 0x57, 0x4c, 0x21, 0x2b, 0x49, 0x35, 0x44, 0xc2,
	0x33, 0xe8, 0x6b, 0xf8, 0xce, 0x7b, 0xd7, 0xbd, 0x9b, 0x91, 0xdf, 0x5f, 0x8b, 0x17, 0xc8, 0x3c,
	0xbd, 0x7f, 0x90, 0x36, 0x78, 0x0e, 0x83, 0x92, 0x57, 0x55, 0x4d, 0xe6, 0x8d, 0x70, 0x02, 0xc3,
	0x45, 0x50, 0xfd, 0x62, 0x59, 0xe7, 0xc7, 0xc9, 0xfc, 0x32, 0xe6, 0x90, 0x2d, 0x37, 0x3a, 0xe3,
	0x35, 0xe5, 0xfd, 0xa4, 0x3a, 0x2c, 0x9e, 0x61, 0xe8, 0x49, 0x77, 0xbc, 0x55, 0xc2, 0x31, 0x9c,
	0xcc, 0x45, 0x58, 0x2c, 0xb8, 0x85, 0xfd, 0x7b, 0x73, 0x91, 0x52, 0xa3, 0xa5, 0x1a, 0xe1, 0x05,
	0x8c, 0x96, 0xa4, 0x5a, 0xf1, 0xf6, 0xf1, 0xc1, 0x52, 0xff, 0x06, 0x77, 0xaf, 0x90, 0x59, 0x31,
	0x7c, 0x82, 0xd3, 0x59, 0xa8, 0xeb, 0x0e, 0x2f, 0xdd, 0x7f, 0xf5, 0x9d, 0xd5, 0x9b, 0x5c, 0x1d,
	0xd2, 0xed, 0x27, 0x8b, 0xa3, 0xd5, 0x20, 0x6d, 0xf1, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x44,
	0x7d, 0x66, 0xff, 0x64, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostRegClient is the client API for PostReg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostRegClient interface {
	CallPostReg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type postRegClient struct {
	cc *grpc.ClientConn
}

func NewPostRegClient(cc *grpc.ClientConn) PostRegClient {
	return &postRegClient{cc}
}

func (c *postRegClient) CallPostReg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.PostReg.PostReg/CallPostReg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostRegServer is the server API for PostReg service.
type PostRegServer interface {
	CallPostReg(context.Context, *Request) (*Response, error)
}

// UnimplementedPostRegServer can be embedded to have forward compatible implementations.
type UnimplementedPostRegServer struct {
}

func (*UnimplementedPostRegServer) CallPostReg(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPostReg not implemented")
}

func RegisterPostRegServer(s *grpc.Server, srv PostRegServer) {
	s.RegisterService(&_PostReg_serviceDesc, srv)
}

func _PostReg_CallPostReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostRegServer).CallPostReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.PostReg.PostReg/CallPostReg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostRegServer).CallPostReg(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostReg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.PostReg.PostReg",
	HandlerType: (*PostRegServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPostReg",
			Handler:    _PostReg_CallPostReg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PostReg/PostReg.proto",
}
