// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetSession/GetSession.proto

package go_micro_srv_GetSession

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"

	context "context"

	client "github.com/micro/go-micro/client"

	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetSession service

type GetSessionService interface {
	CallGetSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getSessionService struct {
	c    client.Client
	name string
}

func NewGetSessionService(name string, c client.Client) GetSessionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetSession"
	}
	return &getSessionService{
		c:    c,
		name: name,
	}
}

func (c *getSessionService) CallGetSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetSession.CallGetSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSession service

type GetSessionHandler interface {
	CallGetSession(context.Context, *Request, *Response) error
}

func RegisterGetSessionHandler(s server.Server, hdlr GetSessionHandler, opts ...server.HandlerOption) error {
	type getSession interface {
		CallGetSession(ctx context.Context, in *Request, out *Response) error
	}
	type GetSession struct {
		getSession
	}
	h := &getSessionHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSession{h}, opts...))
}

type getSessionHandler struct {
	GetSessionHandler
}

func (h *getSessionHandler) CallGetSession(ctx context.Context, in *Request, out *Response) error {
	return h.GetSessionHandler.CallGetSession(ctx, in, out)
}
