// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetHouseInfo/GetHouseInfo.proto

package go_micro_srv_GetHouseInfo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ec40adbebec6fc2, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	HouseID              string   `protobuf:"bytes,2,opt,name=HouseID,proto3" json:"HouseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ec40adbebec6fc2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Request) GetHouseID() string {
	if m != nil {
		return m.HouseID
	}
	return ""
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	HouseInfoBytes       []byte   `protobuf:"bytes,4,opt,name=houseInfoBytes,proto3" json:"houseInfoBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ec40adbebec6fc2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Response) GetHouseInfoBytes() []byte {
	if m != nil {
		return m.HouseInfoBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetHouseInfo.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetHouseInfo.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetHouseInfo.Response")
}

func init() {
	proto.RegisterFile("proto/GetHouseInfo/GetHouseInfo.proto", fileDescriptor_1ec40adbebec6fc2)
}

var fileDescriptor_1ec40adbebec6fc2 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xd5, 0xc6, 0x0e, 0x45, 0xca, 0x20, 0xb2, 0x7e, 0x1c, 0xca, 0x8a, 0xd2, 0xd3,
	0x0a, 0xfa, 0x0b, 0xd4, 0x14, 0xcd, 0xa1, 0x97, 0x88, 0x47, 0x0f, 0x51, 0xc6, 0x58, 0x68, 0x33,
	0x75, 0x66, 0x2b, 0xf6, 0xdf, 0x4b, 0xb3, 0x5b, 0x6c, 0x05, 0xbd, 0xe5, 0x79, 0xe6, 0x9d, 0xb0,
	0xef, 0xc0, 0xf9, 0x4c, 0xd8, 0xf3, 0xe5, 0x3d, 0xf9, 0x07, 0x9e, 0x2b, 0xe5, 0xf5, 0xdb, 0x26,
	0xb8, 0x66, 0x8e, 0x47, 0x15, 0xbb, 0xe9, 0xf8, 0x55, 0xd8, 0xa9, 0x7c, 0xba, 0xf5, 0x80, 0x3d,
	0x81, 0x74, 0x44, 0xaa, 0x65, 0x45, 0xd8, 0x83, 0x96, 0x96, 0x0b, 0x93, 0xf4, 0x93, 0x41, 0xa7,
	0x58, 0x7e, 0xda, 0x1b, 0x48, 0x0b, 0xfa, 0x98, 0x93, 0x7a, 0x3c, 0x85, 0xce, 0x23, 0xa9, 0x8e,
	0xb9, 0xce, 0xb3, 0x18, 0xf9, 0x11, 0x68, 0x20, 0x0d, 0xbf, 0xcc, 0xcc, 0x76, 0x33, 0x5b, 0xa1,
	0xfd, 0x82, 0xbd, 0x82, 0x74, 0xc6, 0xb5, 0x12, 0x1e, 0xc0, 0xee, 0x50, 0x84, 0x25, 0xee, 0x07,
	0xc0, 0x43, 0x68, 0x0f, 0x45, 0x46, 0x5a, 0xc5, 0xd5, 0x48, 0x4b, 0xff, 0xa4, 0x24, 0x79, 0x66,
	0x5a, 0xc1, 0x07, 0xc2, 0x0b, 0xd8, 0x7f, 0x5f, 0x3d, 0xff, 0x76, 0xe1, 0x49, 0xcd, 0x4e, 0x3f,
	0x19, 0x74, 0x8b, 0x5f, 0xf6, 0x6a, 0x0a, 0xdd, 0xf5, 0xa6, 0xf8, 0x0c, 0xbd, 0xbb, 0x72, 0x32,
	0xd9, 0x70, 0xd6, 0xfd, 0x79, 0x19, 0x17, 0x9b, 0x1f, 0x9f, 0xfd, 0x9b, 0x09, 0xd5, 0xec, 0xd6,
	0x4b, 0xbb, 0x39, 0xf5, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x13, 0xec, 0x5f, 0x93,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetHouseInfoClient is the client API for GetHouseInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetHouseInfoClient interface {
	CallGetHouseInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getHouseInfoClient struct {
	cc *grpc.ClientConn
}

func NewGetHouseInfoClient(cc *grpc.ClientConn) GetHouseInfoClient {
	return &getHouseInfoClient{cc}
}

func (c *getHouseInfoClient) CallGetHouseInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.GetHouseInfo.GetHouseInfo/CallGetHouseInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetHouseInfoServer is the server API for GetHouseInfo service.
type GetHouseInfoServer interface {
	CallGetHouseInfo(context.Context, *Request) (*Response, error)
}

// UnimplementedGetHouseInfoServer can be embedded to have forward compatible implementations.
type UnimplementedGetHouseInfoServer struct {
}

func (*UnimplementedGetHouseInfoServer) CallGetHouseInfo(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallGetHouseInfo not implemented")
}

func RegisterGetHouseInfoServer(s *grpc.Server, srv GetHouseInfoServer) {
	s.RegisterService(&_GetHouseInfo_serviceDesc, srv)
}

func _GetHouseInfo_CallGetHouseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetHouseInfoServer).CallGetHouseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.GetHouseInfo.GetHouseInfo/CallGetHouseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetHouseInfoServer).CallGetHouseInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetHouseInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.GetHouseInfo.GetHouseInfo",
	HandlerType: (*GetHouseInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallGetHouseInfo",
			Handler:    _GetHouseInfo_CallGetHouseInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/GetHouseInfo/GetHouseInfo.proto",
}
